# Stage 1: Build the Vue app
FROM node:20-alpine AS builder

WORKDIR /app
COPY frontend/package*.json .
RUN npm ci --silent

COPY frontend/ .
RUN npm run build


# Stage 2: Serve with Nginx
FROM nginx:alpine AS runtime

COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
